name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'explorer/**'
      - '.github/workflows/preview.yml'

concurrency:
  group: preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      deployments: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: explorer/yarn.lock

      - name: Install dependencies
        working-directory: explorer
        run: yarn install --frozen-lockfile

      - name: Build project
        working-directory: explorer
        run: yarn build

      - name: Deploy Preview
        id: deploy
        working-directory: explorer
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          # Deploy to preview environment
          output=$(npx wrangler pages deploy dist \
            --project-name=qsafe \
            --branch=pr-${{ github.event.pull_request.number }} \
            --commit-hash=${{ github.event.pull_request.head.sha }} \
            2>&1 | tee deploy.log)
          
          # Extract the preview URL
          preview_url="https://pr-${{ github.event.pull_request.number }}.qsafe.pages.dev"
          echo "preview_url=$preview_url" >> $GITHUB_OUTPUT

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '🚀 Preview Deployment'

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🚀 Preview Deployment
            
            Your preview is ready! 
            
            | Status | Preview URL | Commit |
            |--------|-------------|--------|
            | ✅ Success | [${{ steps.deploy.outputs.preview_url }}](${{ steps.deploy.outputs.preview_url }}) | ${{ github.event.pull_request.head.sha }} |
            
            ---
            <sub>Updated: ${{ github.event.pull_request.updated_at }}</sub>
          edit-mode: replace